fmt: go fmt project
metrumresearchgroup/bbi pull request #206
Opened 2021-01-18 23:45 UTC by dpastoor

go fmt project and cleaned up some misc top level files that were legacy

2021-01-19 21:06 UTC, seth127 requested changes
I like this housekeeping PR and I'd like to merge it, but I'm not sure if you were done with it or not. Either way, there are one or two things that appear unfinished.

2021-01-19 21:06 UTC, seth127 commented on README.md
>   * `/abs/path/to/file.mod` : The location of the file to submit for execution. Can be relative or absolute.
This should probably be `path/to/file.mod` too for consistency

2021-01-19 21:06 UTC, seth127 commented on README.md
> +
Both of these examples appear to be blank... Did you want to replace those with something or should we scrap this whole section?

2021-01-19 21:06 UTC, seth127 commented on README.md
Is the section below still correct? I don't think so, but I could be wrong. If it's not, let's just remove it for now.

2021-01-19 21:15 UTC, seth127 commented
related: is this branch stale? It looks like most, if not all, of the changes from it have been done in this branch now
https://github.com/metrumresearchgroup/bbi/pull/200

If so, let's close and delete the other one from December.

2021-01-19 23:56 UTC, dpastoor commented
Thanks for the feedback!

2021-01-20 02:06 UTC, dpastoor commented
> related: is this #200 branch/PR stale? It looks like most, if not all, of the changes from it have been done in this branch now.
> 
> If so, let's close and delete the other one from December.

Yes I followed the same procedure here as that other branch did not want to attempt to reconcile with the naming changes from the previous one so figured would just start a new one Will close #200 out

2021-01-21 15:30 UTC, seth127 approved these changes
Looks good

2021-01-21 15:31 UTC, merged